### ISSUE TITLE
AlloyEditor.React is undefined after upgrading 

### ISSUE THREAD

**Issue by lpsBetty** [liferay/alloy-editor#1189]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I added custom buttons with `var React = AlloyEditor.React`, but `AlloyEditor.React` is not available anymore. As described [here](https://alloyeditor.com/docs/develop/create_buttons.html).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Install the latest version of Alloy-editor (2.0.0-beta.3). Try to access `AlloyEditor.React` in the console - it will be undefined.

**What is the expected behavior?**
I would like to access React and create Buttons.

**Which versions of alloy-editor, and which browser / OS are affected by this issue? Did this work in previous versions?**
Chrome on macOS,  Alloy-editor 2.0.0-beta.3
It worked with Alloy-editor 1.5.19

**Comment by lpsBetty** [comment]
@julien i still got 1 error now:

```
Uncaught TypeError: React.createClass is not a function
```

Has the method name been changed? I create the buttons like described in your [documentation](https://alloyeditor.com/docs/develop/create_buttons.html).

**Comment by julien** [comment]
Hi @lpsBetty,

Yes that error was expected.

First of all, it's tue that we need to update our documentation, apologies for not having done so.

`React.createClass` was actually removed a [while back](https://reactjs.org/blog/2017/09/26/react-v16.0.html) from `React` itself and now the way to create `React` components is done by extending the `Component` class like so:

```javascript
import React from 'react';

class MyComponent extends React.Component {

}
```

You can have a look at some existing [**button** components](https://github.com/liferay/alloy-editor/tree/master/src/components/buttons) to have a more detailed example.

Let me know if that helps.
